commonLabels:
  demo-mode: "true"
image:
  registry: "docker.io"
  tag: "stable-alpine3.23-perl"
  repository: "nginx"
replicaCount: 1
service:
  type: "ClusterIP"
  ports:
    http: 80
containerSecurityContext:
  readOnlyRootFilesystem: false
  runAsUser: 1001
  runAsGroup: 1001
